### ISSUE TITLE
Dimension differences for .CR3 files between DeepSkyStacker and Camera Raw (ACR)

### ISSUE THREAD

**Issue by szotsaki** [deepskystacker/DSS#119]
When you open a .CR3 file in DeepSkyStacker, it reports its dimension to be 6984×4660 pixels. When you open it in ACR, the same file is reported to be 6960×4640 pixels in size. That is a difference of 24×20 pixels which makes it impossible to pre-process the light frames into TIFF and use raw CR3 dark frames at the same time.

I uploaded a sample CR3 file and a TIFF made from it here: https://mega.nz/folder/RERBBC6Z#mUmzDupDS12MH3SCmWBixg

DSS version: 4.2.4.

**Comment by perdrix52** [comment]
I have no control over what LibRaw does about the image size for CR3 files.

Please could I ask you to raise this problem with the LibRaw folks at LibRaw.org.  Maybe they'll listen to you.  PS Why on earth would you want to convert you light frames to TIFF?  DNG maybe, but TIFF?

David

**Comment by szotsaki** [comment]
I reported the issue for LibRaw here: https://github.com/LibRaw/LibRaw/issues/332.

:) Well, so far I've always considered DNG as an archive format into which I'll have to convert my proprietary RAW files in the long term but never as an intermediate format to be exported to after the necessary pre-processing (to reduce light pollution, for example). Thank you for the suggestion, I think I'll try DNG instead of TIFF next time since I anyway want to preserve them.

**Comment by szotsaki** [comment]
Could you please take another look at the above linked issue? What I could understand, that using `raw_inset_crop` ([an example](https://github.com/LibRaw/LibRaw/blob/master/samples/raw-identify.cpp#L1267)) could be a solution for this problem (but I'm not sure).

You can find several RAW files to test with at https://raw.pixls.us/#repo.

**Comment by perdrix52** [comment]
I've read the linked discussion of Libraw  issue #332

My problem here is which to choose - I'm using the "default" at present - you can guarantee that if I change someone will get upset because the image size has changed (shrunk in this case).

I think that this issue needs to be discussed on the DeepSkyStacker mailing list as it isn't clear what the "correct" answer is/should be.   Please could I ask you to provide introduce the problem as in your first entry here, and then add a short bit about raw_inset_crop and provide the output from the raw-identify utility 

Do you know if this applies ONLY to the EOS 90D, or to all CR3 images.
