### ISSUE TITLE
Virus in 4.2.6 installer

### ISSUE THREAD

**Issue by marekbohdan** [deepskystacker/DSS#134]
Hi!
When downloading the installer of version 4.2.6, the antivirus reports to me the existence of Win32/FormBook.AVP! MTB virus. Both the x86 and x64 versions. What's the problem?

**Comment by perdrix52** [comment]
I’m pretty certain it is a false positive – submit the installer to your AV provider to confirm.   I’ve had this sort of issue reported before where the problem was simply that the AV hadn’t seen that installer before.   No actual infections found.

 

What AV are you using?

 

David

 

From: marekbohdan ***@***.***> 
Sent: 01 July 2021 12:40
To: deepskystacker/DSS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [deepskystacker/DSS] Virus in 4.2.6 installer (#134)

 

Hi!
When downloading the installer of version 4.2.6, the antivirus reports to me the existence of Win32/FormBook.AVP! MTB virus. Both the x86 and x64 versions. What's the problem?

**Comment by marekbohdan** [comment]
I'm using Windows Defender (Windows 10).

**Comment by perdrix52** [comment]
Windows Defender says it is clean, as does MalwareBytes.

 

David

 

From: David C. Partridge ***@***.***> 
Sent: 01 July 2021 13:03
To: 'deepskystacker/DSS' ***@***.***>
Subject: RE: [deepskystacker/DSS] Virus in 4.2.6 installer (#134)

 

I’m pretty certain it is a false positive – submit the installer to your AV provider to confirm.   I’ve had this sort of issue reported before where the problem was simply that the AV hadn’t seen that installer before.   No actual infections found.

 

What AV are you using?

 

David

 

From: marekbohdan ***@***.*** ***@***.***> > 
Sent: 01 July 2021 12:40
To: deepskystacker/DSS ***@***.*** ***@***.***> >
Cc: Subscribed ***@***.*** ***@***.***> >
Subject: [deepskystacker/DSS] Virus in 4.2.6 installer (#134)

 

Hi!
When downloading the installer of version 4.2.6, the antivirus reports to me the existence of Win32/FormBook.AVP! MTB virus. Both the x86 and x64 versions. What's the problem?
