### ISSUE TITLE
Incorrect temp directory, 5.1.5, Windows 11

### ISSUE THREAD

**Issue by cykelstativet** [deepskystacker/DSS#204]
**Version 5.1.5, Windows 11 21H2 22000**

**Describe the bug**
Temporary files are created NEXT to the selected directory, instead of INSIDE the directory. If the selected directory is "C:\temp\" then the files will be found at "C:\dssfile.tmp\" instead of "C:\temp\dssfile.tmp\".

**Provide necessary data to reproduce the problem**
Install DSS and stack images. I have tried reinstalling the application, as well as clearing all settings and files related to DSS.

**To Reproduce**
1. Go to 'Stack Checked Pictures'.
2. Click on 'Stacking Settings'.
3. Click on 'Temporary files folder'.
4. Select the directory where temporary files should be created.

**Expected behavior**
Temporary files are created inside the selected directory.

**Additional context**
I suspect that DSS simply lacks a '/' at the end of the path. The temp files appear to have the directory appended in the beginning of the files. So if the selected directory is called "temp" the files will be called "tempDSSxxxxx.tmp". If the directory is "dssfiles" the files will be called "dssfilesDSSxxxxx.tmp".

**Comment by perdrix52** [comment]
Thank you for that diagnosis.    I think you’re absolutely correct.

 

I’m in the throes of a house move (move date 2st Feb.) so won’t have time to write a fix myself.

 

Perhaps one of the other devs (Simon?) could look at the code in question and fix it?

 

 

 

 

From: cykelstativet ***@***.***> 
Sent: 27 January 2024 09:36
To: deepskystacker/DSS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [deepskystacker/DSS] Incorrect temp directory, 5.1.5, Windows 11 (Issue #204)

 

Version 5.1.5, Windows 11 21H2 22000

Describe the bug
Temporary files are created NEXT to the selected directory, instead of INSIDE the directory. If the selected directory is "C:\temp" then the files will be found at "C:\dssfile.tmp" instead of "C:\temp\dssfile.tmp".

Provide necessary data to reproduce the problem
Install DSS and stack images. I have tried reinstalling the application, as well as clearing all settings and files related to DSS.

To Reproduce
Steps to reproduce the behavior:

1.	Go to 'Stack Checked Pictures'.
2.	Click on 'Stacking Settings'.
3.	Click on 'Temporary files folder'.
4.	Select the directory where temporary files should be created.

Expected behavior
Temporary files are created inside the selected directory.

Additional context
I suspect that DSS simply lacks a '/' at the end of the path. The temp files appear to have the directory appended in the beginning of the files. So if the selected directory is called "temp" the files will be called "tempDSSxxxxx.tmp". If the directory is "dssfiles" the files will be called "dssfilesDSSxxxxx.tmp".

**Comment by perdrix52** [comment]
I managed to find some time to look at this.  Are you up for testing a fix?

David

**Comment by cykelstativet** [comment]
Sorry for the delay, I didn't get my email notification..

> I managed to find some time to look at this. Are you up for testing a fix?

Absolutely :)

**Comment by cykelstativet** [comment]
After next to no testing - just did one stack of the 45 minutes I happened to capture this night - it does indeed seem to work. All stacks on the official release had the same issue, so even a single stack that doesn't do it is proof enough for me :)

**Comment by perdrix52** [comment]
Many thanks, that will be fixed in the next release
