### ISSUE TITLE
Any chance for a OSX version?

### ISSUE THREAD

**Issue by theDiverDK** [deepskystacker/DSS#58]
Hi there

As a fellow developer, I know this is a big task.

But any plans on making an OSX version? Maybe by utilising QT for the UI?

**Comment by perdrix52** [comment]
The code is so deeply tied to the MFC and GDI+ that the answer has to be no (unless you feel you can handle this)?

**Comment by theDiverDK** [comment]
I would love to help, but unfortunately i have not been working with MFC or gdi+ since many years ago.

Have been doing fullstack web development for years.

**Comment by JamesMolson** [comment]
I could do this, but would the current maintainers be ok with the vast level of changes required to make it more platform generic?

**Comment by wornish** [comment]
I am sure it would be well received.

**Comment by perdrix52** [comment]
James,

 

Before you commit that this is feasible have you studied the existing code – it will not be a quick and easy change for sure …

 

I assume you would take the approach of using something like Qt for porting the UI ?

 

I’m not “agin it” so long as you let us old codgers come up to speed slowly by somehow doing it one step at a time so we can get our heads round how it’s done.    

 

It appears that Intel Parallel Studio supports MacOS so if they offer the MacOs version free of charge(*) to Open Source developers, we could portably move to that as a common cross platform build environment.

 

(*)  I just checked and AFAICT           they only offer the Linux version free for OpenSource L

 

David

**Comment by avarakin** [comment]
I think the easier route would be to use Wine. I tried DSS under wine many years ago and it almost worked.

**Comment by michalsc** [comment]
I have been using DSS with wine long time ago with some minor results. It was working more or less but it was much more pleasant to switch to a windows machine instead.

I think porting to multiplatform toolkit like Qt would be a huge effort, most likely not feasible for a single person. But I am also pretty sure if you would agree on that, in form of a fork with subsequent pull requests or separate branch in main repository, then it would be possible to form a small team of Qt developers doing it.

**Comment by perdrix52** [comment]
I'm actively looking at this again ... I've ordered a book on Qt.

This will not happen in the upcoming release, but the one after that and it will take time.

D.

**Comment by michalsc** [comment]
@perdrix52 let me know if you need any help on Qt. I have been using this toolkit in several projects already.

**Comment by michalsc** [comment]
@perdrix52 I have downloaded vs2017 and opened the dss project there. Now, since I see all dialogs there, I could create the corresponding dialogs in Qt5. How about that? I would work on my forked version of DSS: https://github.com/michalsc/DSS/tree/Qt-gui and eventually send pull requests from there. How about that?

**Comment by michalsc** [comment]
in https://github.com/michalsc/DSS/tree/Qt-gui/qt directory you can find the AskRegistering dialog as an example of how things could be done in Qt5. The dialog consists of an .ui file, generated by the designer and compiled automatically by qt and typical header and cpp file as it is in case of MFC too. The dialog is fully functioning and selecting one of registering option sets the m_Result accordingly. The m_Result is read the same was as in case of MFC dialog - through AskRegistering::GetAction() method. The dialog looks like this (macOS, dark theme):

![Preview](https://imgur.com/VJrdK0V)

Please note the translations can be added later, all strings in ui are automatically passed through QCoreApplication::translate() method. We also don't need html library of any kind since Qt labels support quite usable subset of HTML tags.

Shall I continue?

**Comment by perdrix52** [comment]
Hi Michael, thanks - Ive just installed Qt 5.12.8 (latest of the LTS version) - OpenSource.

I'm trying to work out how to convert my VS2017 project to be able to use Qt with it - I'm sure it will be easy but so far ... (see my post on the Qt Forum under handle Perdrix).

Once I've got that worked out, I'll replace the use of the CRegistry class with Qsettings in the Workspace.   I'm not quite sure right now whether to instantiate a QApplication instance in the existing WinMain or what?

I thought I'd invited you to our Slack?  If so can we continue this there, as that's where all the DSS devs hang out.

David

**Comment by perdrix52** [comment]
If it wasn't you I invited please let me know your email and full name and I'll invite you

**Comment by michalsc** [comment]
I haven't noticed invitation yet. please send it to michal (dot) schulz (at) gmx (dot) de. Once I receive it I will reedit this message ;)

**Comment by avarakin** [comment]
I tried running latest DSS under wine but it crashes as soon it starts stacking.
Looking forward to trying out QT based version.

**Comment by perdrix52** [comment]
Me too, but please don’t hold your breath – Version 5 will take a while

 

David

**Comment by pludov** [comment]
I am using DSS under linux/wine : The command line version works fine so far. The UI often loose some settings so I mostly use it to understand the dssfilelist format.

**Comment by perdrix52** [comment]
I don't have a clue about Wine, so I can't help you

**Comment by danielpox** [comment]
Any updates on this?

**Comment by perdrix52** [comment]
I was able to work on this for the first 4 months of 2021, but since then for various reasons haven’t had time to do so.

 

I hope to get back to this early next year.

 

David

**Comment by perdrix52** [comment]
On completion of Qt migration this will be possible
