### ISSUE TITLE
Stacking problem( canon 6d)

### ISSUE THREAD

**Issue by qendis** [deepskystacker/DSS#92]
Hi!
The problem is as in the attached picture.
when I stack photos from a Canon 450 d, it's all good.
The problem occurs with the full frame Canon 6d.
Do you have any ideas?

![Autosave005](https://user-images.githubusercontent.com/61312057/75021511-d1349a80-5494-11ea-997e-1e09bc1b94d8.jpg)

**Comment by perdrix52** [comment]
You could try changing the Stacking Settings Alignment tab to use (say) Bi-Linear instead of Auto.  I suspect you didn't have very many light frames and that this is a wide angle shot.

If that doesn't work, please report this on the DeepSkyStacker mailing list at groups.io which is where this sort of thing should go.

**Comment by qendis** [comment]
Hi, I tried different settings. Unfortunately it does not work. The focal length is 135 mm. PixInsigh has stacked up the photos well.
